{
    'name': 'Captcha for Odoo',
    'version': '18.0.1.0.0',
    'summary': 'Add captcha verification to Login, Signup, Reset Password forms with multiple captcha types.',
    "category": "Extra Tools",
    "author": "Zehntech Technologies Inc.",
    "company": "Zehntech Technologies Inc.",
    "maintainer": "Zehntech Technologies Inc.",
    "contributor": "Zehntech Technologies Inc.",
    "website": "https://www.zehntech.com/",
    "support": "odoo-support@zehntech.com",
    'license': 'LGPL-3',
    'depends': ['base','website', 'web','web_editor', 'auth_signup'],
    'data': [
        "security/ir.model.access.csv",
        # 'views/template.xml',
        'views/res_config_settings_views.xml',
        # 'views/captcha_config_wizard_views.xml',
        'views/captcha_templates.xml',
    ],
    'assets': {
        "web.assets_frontend": [
            "zehntech_captcha_for_odoo/static/src/scss/captcha.scss",
        ],
        'web.assets_backend': [
            "zehntech_captcha_for_odoo/static/src/js/captcha_settings.js",
        ],
        'website.assets_wysiwyg': [
            'zehntech_captcha_for_odoo/static/src/js/backend_captcha.js',
            'zehntech_captcha_for_odoo/static/src/js/captcha_editor.js',
        ],
    },
    # "live_test_url": "https://zehntechodoo.com/app_name=zehntech_captcha_for_odoo/app_version=18.0",
    'installable': True,
    'application': False,
    'auto_install': False,
    "images": ["static/description/banner.gif"],
    'price': 00.00,
    'currency': 'USD',
}